<template>
<div id="footer">
   <ul>
     <li>
       <router-link to="index">
         <span class="icon-1-07"></span>
         <p>首页</p>
       </router-link>
     </li>
     <li>
       <router-link to="index">
         <span class="icon-1-07"></span>
         <p>首页</p>
       </router-link>
     </li>
     <li>
       <router-link to="index">
         <span class="icon-1-07"></span>
         <p>首页</p>
       </router-link>
     </li>
     <li>
       <router-link to="index">
         <span class="icon-1-07"></span>
         <p>首页</p>
       </router-link>
     </li>
     <li>
       <router-link to="index">
         <span class="icon-1-07"></span>
         <p>首页</p>
       </router-link>
     </li>
   </ul>

</div>

</template>

<script>


</script>

<style>


</style>
